color = input("Enter a Color: ")
pluralNoun = input("Enter a Plural Noun: ")
celebrity = input("Enter the name of a celebrity: ")
print("Rose is", color)
print(pluralNoun, "are blue")
print("I like", celebrity)